# Generated by Django 4.2.5 on 2023-10-30 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_article_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
