# Generated by Django 4.2.5 on 2023-10-30 23:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0005_remove_article_name_article_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="publish",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
