# Generated by Django 4.2.5 on 2023-10-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0006_article_publish"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
